### ISSUE TITLE
improve compactor

### ISSUE THREAD

**Issue by oalam** [Hurence/historian#195]
for now we've got one compactor job with one conf
  
  ```yaml
  
  reader:
      queryFilters: "chunk_origin:prometheus-scraper"
  
  chunkyfier:
      saxAlphabetSize: 7
      saxStringLength: 24
      origin: "compactor"
      dateBucketFormat: "yyyy-MM-dd.HH"
  
  scheduler:
      period: 10
      startNow: true
```

  
  we must be able to add multiples conf in order to handle multiples workloads of compaction.
  
  for example one metric could be done hourly for the current day and daily for the previous day
  
  ```yaml
compactions:
    - id: hourly_scrapping_compaction
      reader:
          queryFilters: "chunk_origin:prometheus-scraper"
      chunkyfier:
          saxAlphabetSize: 7
          saxStringLength: 30
          origin: "prometheus-scraper-compacted-hourly"
          dateBucketFormat: "yyyy-MM-dd.HH"
      scheduler:
          period: 10
          startNow: true
    - id: daily_scrapping_compaction
      reader:
          queryFilters: "chunk_origin:prometheus-scraper-compacted-hourly"
      chunkyfier:
          saxAlphabetSize: 7
          saxStringLength: 24
          origin: "prometheus-scraper-compacted-daily"
          dateBucketFormat: "yyyy-MM-dd"
      scheduler:
          period: 86400
          startNow: true
  ```
